### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by leimu12** [Rovniced/ArkLights#7]
大佬好像软件不能更新了。

**Comment by Rovniced** [comment]
> 大佬好像软件不能更新了。

提示什么 截个图

**Comment by leimu12** [comment]
最新版是10.12吗，中间我看更新了。

**Comment by leimu12** [comment]
最新版是10.12吗，中间我看更新了，现在显示10.12是最新版，之前的时候提示待切换更新地址

**Comment by Rovniced** [comment]
> 最新版是10.12吗，中间我看更新了，现在显示10.12是最新版，之前的时候提示待切换更新地址

是的 更新服务器有很多个，如果有哪个坏了会自动切换其他的

**Comment by leimu12** [comment]
好的，谢谢
